apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
 name: gcs-object-finalize
spec:
  type: com.google.storage.finalize
  importer:
    apiVersion: sources.aikas.org/v1alpha1
    kind: GCSSource
    parameters:
    - name: secretName
      description: "Name of a Secret containing a GCP service account key with permission to create a GCP notification. Must be at the `key.json` key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys)."
    - name: googleCloudProject
      description: "Google Cloud Project ID containing the bucket."
    - name: bucket
      description: "GCS bucket to subscribe to. For example my-test-bucket"

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
 name: gcs-object-archive
spec:
  type: com.google.storage.archive
  importer:
    apiVersion: sources.aikas.org/v1alpha1
    kind: GCSSource
    parameters:
    - name: secretName
      description: "Name of a Secret containing a GCP service account key with permission to create a GCP notification. Must be at the `key.json` key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys)."
    - name: googleCloudProject
      description: "Google Cloud Project ID containing the bucket."
    - name: bucket
      description: "GCS bucket to subscribe to. For example my-test-bucket"

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
 name: gcs-object-delete
spec:
  type: com.google.storage.delete
  importer:
    apiVersion: sources.aikas.org/v1alpha1
    kind: GCSSource
    parameters:
    - name: secretName
      description: "Name of a Secret containing a GCP service account key with permission to create a GCP notification. Must be at the `key.json` key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys)."
    - name: googleCloudProject
      description: "Google Cloud Project ID containing the bucket."
    - name: bucket
      description: "GCS bucket to subscribe to. For example my-test-bucket"

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
 name: gcs-object-metadataUpdate
spec:
  type: com.google.storage.metadataUpdate
  importer:
    apiVersion: sources.aikas.org/v1alpha1
    kind: GCSSource
    parameters:
    - name: secretName
      description: "Name of a Secret containing a GCP service account key with permission to create a GCP notification. Must be at the `key.json` key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys)."
    - name: googleCloudProject
      description: "Google Cloud Project ID containing the bucket."
    - name: bucket
      description: "GCS bucket to subscribe to. For example my-test-bucket"

---



